apiVersion: v1
kind: Service
metadata:
  name: hello-server
  labels:
    component: hello-server
spec:
  type: NodePort
  selector:
    component: hello-server
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 3000
    nodePort: 30000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-server
  labels:
    component: hello-server
spec:
  replicas: 3
  selector:
    matchLabels:
      component: hello-server
  template:
    metadata:
      labels:
        component: hello-server
    spec:
      containers:
      - name: hello-server
        image: andreasatle/hellov2-grpc-server
        ports:
        - containerPort: 3000
        env:
        - name: HOST_HELLO_WORKER
          value: hello-worker

